### ISSUE TITLE
Unused variable should be removed

### ISSUE THREAD

**Issue by eduardokraus** [dev-capsule/moodle-block_su_agent_moodle#1]
It was identified that a variable has been declared in the code but is not being used anywhere. The presence of this unnecessary variable can affect code readability and increase complexity.

![Captura de Tela 2024-12-10 às 07 50 37](https://github.com/user-attachments/assets/5205af48-1e61-47e8-aa46-913df149cdb2)

**Comment by dev-capsule** [comment]
done
