### ISSUE TITLE
Improve Comment Block Indentation in Code

### ISSUE THREAD

**Issue by eduardokraus** [dev-capsule/moodle-block_su_agent_moodle#2]
Description: The indentation of comment blocks can be improved to make the code more organized and visually appealing. This enhances readability and comprehension, especially in longer or more complex code sections, and follows good coding practices.

![Captura de Tela 2024-12-10 às 07 55 59](https://github.com/user-attachments/assets/c5075eb0-6001-4031-bcf0-79cef14b54e6)

**Comment by dev-capsule** [comment]
done
