### ISSUE TITLE
Getting the User's IP

### ISSUE THREAD

**Issue by eduardokraus** [dev-capsule/moodle-block_su_agent_moodle#3]
When attempting to obtain the user's IP address in Moodle, use the getremoteaddr() function, which must be implemented correctly to ensure the correct IP address is captured.

![Captura de Tela 2024-12-10 às 08 05 34](https://github.com/user-attachments/assets/b51f8e58-8f48-471b-8d77-e20b17f41c6d)

**Comment by dev-capsule** [comment]
done
