### ISSUE TITLE
Replace $_POST with optional_param() or required_param()

### ISSUE THREAD

**Issue by eduardokraus** [dev-capsule/moodle-block_su_agent_moodle#4]
In the current code, `$_POST` is being used directly to retrieve parameters. It is recommended to replace the use of `$_POST` with the Moodle functions `optional_param()` or `required_param()`, depending on whether the parameters are optional or required.

- **optional_param()**: For optional parameters that may or may not be passed in the request.
- **required_param()**: For required parameters that must be provided.

#### Replace:
```php
$param = $_POST['message'];
```

#### With:
```php
$param = required_param('message', PARAM_TEXT);  // if required
// or
$param = optional_param('message', '', PARAM_TEXT);  // if optional
```

![Captura de Tela 2024-12-10 às 08 07 15](https://github.com/user-attachments/assets/4fc24f8c-b416-4d10-8cf0-2b0c3890ea48)

**Comment by dev-capsule** [comment]
done

**Comment by dev-capsule** [comment]
Hello @volodymyrdovhan , is it okay for you? What’s the next step in the process?
